name: tpg-extractor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.0
  - openpyxl=3.1.2
  - pip
  - pip:
    - PyPDF2==3.0.1
    - gspread==5.10.0
    - oauth2client==4.1.3

  